dist: trusty

sudo: required

language: java

jdk:
  - openjdk7

before_install:
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x -y
  - sudo apt-get update && sudo apt-get install cmake -y
  - wget -qO- https://github.com/google/protobuf/archive/v3.1.0.tar.gz | tar -xvz -C /tmp
  - cd /tmp/protobuf-3.1.0 && bash autogen.sha && ./configure && make && sudo make install

script:
  - mkdir build
  - cd build
  - cmake .. && make && make test

addons:
  apt:
    packages:
    - gcc-4.8
    - g++-4.8
    - curl
    - wget
    - build-essential
    - pkg-config
    - unzip
    - autoconf
    - libtool
    - libboost-dev

